version: "3.9"
services:
  backend:
    build:
      context: ./backend
    container_name: springboot-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bookdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    networks:
      - book-net

  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: bookdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - book-net

  frontend:
    build:
      context: ./frontend-simple
    container_name: html-frontend
    ports:
      - "3000:3000"
    networks:
      - book-net

volumes:
  postgres-data:

networks:
  book-net:
